# Generated by Django 4.2.16 on 2025-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("localisation", models.CharField(max_length=255)),
                ("imagelogo", models.ImageField(upload_to="logos/")),
                ("about", models.TextField()),
                ("jour_ouverture", models.CharField(max_length=20)),
                ("jour_fermeture", models.CharField(max_length=20)),
                ("heure_ouverture", models.TimeField()),
                ("heure_fermeture", models.TimeField()),
            ],
        ),
    ]
