# Generated by Django 4.2.16 on 2025-06-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0003_accueilparti1_fond"),
    ]

    operations = [
        migrations.CreateModel(
            name="choix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("imagelogo", models.ImageField(upload_to="logos/")),
            ],
        ),
        migrations.CreateModel(
            name="Defile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
            ],
        ),
    ]
