# Generated by Django 4.2.16 on 2025-06-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0005_remove_choix_imagelogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicule",
            name="disponible",
            field=models.BooleanField(),
        ),
    ]
