# Generated by Django 4.2.16 on 2025-06-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0008_actu_question_impression"),
    ]

    operations = [
        migrations.AddField(
            model_name="actu",
            name="modal",
            field=models.TextField(default="standard"),
        ),
        migrations.CreateModel(
            name="CaracteristiqueTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_sieges", models.PositiveSmallIntegerField(default=5)),
                ("nombre_portes", models.PositiveSmallIntegerField(default=5)),
                ("vitesse_max", models.PositiveSmallIntegerField(help_text="en km/h")),
                ("climatisation", models.BooleanField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("AUTO", "Automatique"), ("MANUEL", "Manuelle")],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                (
                    "carburant",
                    models.CharField(
                        choices=[
                            ("ESSENCE", "Essence"),
                            ("DIESEL", "Diesel"),
                            ("ELECTRIQUE", "Électrique"),
                            ("HYBRIDE", "Hybride"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "consommation",
                    models.FloatField(blank=True, help_text="en L/100km", null=True),
                ),
                (
                    "vehicule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracteristiques",
                        to="Appli.vehicule",
                    ),
                ),
            ],
        ),
    ]
