# Generated by Django 4.2.16 on 2025-06-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0009_actu_modal_caracteristiquetechnique"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="destiation",
            field=models.CharField(default="standard", max_length=55),
        ),
        migrations.AddField(
            model_name="reservation",
            name="lieu_prise",
            field=models.CharField(default="standard", max_length=55),
        ),
    ]
