# Generated by Django 4.2.16 on 2025-06-15 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0010_reservation_destiation_reservation_lieu_prise"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="destiation",
            new_name="destination",
        ),
    ]
