# Generated by Django 4.2.16 on 2025-06-15 00:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0011_rename_destiation_reservation_destination"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-date_creation"],
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="assurance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="date_modification",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="kilometrage_depart",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="kilometrage_retour",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="reservation",
            name="piece_identite_recto",
            field=models.FileField(
                blank=True, null=True, upload_to="pieces_identite/recto/"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="piece_identite_verso",
            field=models.FileField(
                blank=True, null=True, upload_to="pieces_identite/verso/"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("CONFIRME", "Confirmé"),
                    ("EN_COURS", "En cours"),
                    ("TERMINE", "Terminé"),
                    ("ANNULE", "Annulé"),
                ],
                default="EN_ATTENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date_debut",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 6, 15))
                ]
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="destination",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="lieu_prise",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="vehicule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="Appli.vehicule",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(("date_fin__gte", models.F("date_debut"))),
                name="check_date_fin_apres_debut",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut__in", ["CONFIRME", "EN_COURS"])),
                fields=("vehicule", "date_debut", "date_fin"),
                name="unique_reservation_vehicule_periode",
            ),
        ),
    ]
