# Generated by Django 4.2.16 on 2025-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0012_alter_reservation_options_reservation_assurance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
            ],
        ),
    ]
