# Generated by Django 4.2.16 on 2025-06-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0014_remove_reservation_assurance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("fonction", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
