# Generated by Django 4.2.16 on 2025-06-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0016_publicite"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicite",
            name="photo",
            field=models.ImageField(default="standard", upload_to="images/"),
        ),
    ]
