# Generated by Django 4.2.16 on 2025-06-16 00:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0017_publicite_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicite",
            name="titre",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date_debut",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 6, 16))
                ]
            ),
        ),
    ]
