# Generated by Django 4.2.16 on 2025-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0018_alter_publicite_titre_alter_reservation_date_debut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caracteristiquetechnique",
            name="climatisation",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
