# Generated by Django 4.2.16 on 2025-06-27 10:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0019_alter_caracteristiquetechnique_climatisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="annulee",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date_debut",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 6, 27))
                ]
            ),
        ),
    ]
