# Generated by Django 4.2.16 on 2025-06-30 19:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appli", "0020_reservation_annulee_alter_reservation_date_debut"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="photo_profil",
            field=models.ImageField(
                blank=True,
                default="photos_profil/default.jpg",
                null=True,
                upload_to="photos_profil/",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date_debut",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 6, 30))
                ]
            ),
        ),
    ]
